sudo: false
language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  on:
      branch: master
  provider: npm
  email: CalebLemoine@gmail.com
  api_key: $npmToken
